server:
  port: "8080"
  mode: "debug" # release in production

app:
  name: "agentXmap"
  version: "1.0.0"

logger:
  level: "debug" # debug, info, warn, error
  encoding: "json" # json, console

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password" # CHANGE ME
  dbname: "agentxmap"
  sslmode: "disable"
